version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  project: MiniProfiler.Elasticsearch.sln
  verbosity: minimal
after_build:
- cmd: nuget pack ./src/MiniProfiler.Elasticsearch/MiniProfiler.Elasticsearch.nuspec
artifacts:
- path: '*.nupkg'
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: FR4SJS+eNxyKbNj4sYviZE4uayBcvyVm8YbCEwjAGts5O0/nnjqheQKS2F7WNABd
  artifact: nuget
  on:
    APPVEYOR_REPO_TAG: true